apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer  # 外部からアクセスできるように
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend  # Deployment のラベルに一致
